In [78]:
import numpy as np
import pandas as pd

In [79]:
data = pd.read_csv("iris.csv")
data.head() # to get first 5 data on dataset

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [80]:
data.tail() # to get last 5 data in dataset

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [81]:
# to get number of raws and columns
data.shape

(150, 6)

In [82]:
# species column eke thiyena categories wala count eka ganna
data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [83]:
# data set eka wisthara tikak danganna

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [85]:
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [86]:
# feature tika gannawa x widihata
# iloc kiyanne index location
x = data.iloc[:,1:5] 
x.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [87]:
y = data.iloc[:,-1] # -1 kiyala ganne last column eka
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [88]:
# feature scaling

In [89]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [90]:
x = scaler.fit_transform(x)
x[0:5] # x wala mul value 5 balanawa

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [91]:
# Train test split

In [92]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [93]:
x_train.shape

(120, 4)

In [94]:
x_test.shape

(30, 4)

In [95]:
# K-NN algorithm

In [96]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1) # k = 1 kiyala dila (mulin 1 kiyala nikan denawa)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [97]:
pred = model.predict(x_test) # testing eke data tikakata predict karnawa
pred[0:5] # predict karapu eke mul 5

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [98]:
y_test[0:5]

51     Iris-versicolor
50     Iris-versicolor
31         Iris-setosa
108     Iris-virginica
36         Iris-setosa
Name: Species, dtype: object

In [99]:
# To find accuracy

In [100]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, pred)
accuracy

0.9666666666666667

In [101]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred) # wikarnaye thiyena agayan thama true tika
cm

array([[10,  0,  0],
       [ 0,  8,  0],
       [ 0,  1, 11]])

In [102]:
result = pd.DataFrame(data=[y_test.values,pred], index=['y_test','pred'])
result.transpose()

             y_test             pred
0   Iris-versicolor  Iris-versicolor
1   Iris-versicolor  Iris-versicolor
2       Iris-setosa      Iris-setosa
3    Iris-virginica   Iris-virginica
4       Iris-setosa      Iris-setosa
5       Iris-setosa      Iris-setosa
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8   Iris-versicolor  Iris-versicolor
9       Iris-setosa      Iris-setosa
10  Iris-versicolor  Iris-versicolor
11  Iris-versicolor  Iris-versicolor
12   Iris-virginica   Iris-virginica
13   Iris-virginica   Iris-virginica
14      Iris-setosa      Iris-setosa
15   Iris-virginica   Iris-virginica
16  Iris-versicolor  Iris-versicolor
17   Iris-virginica   Iris-virginica
18  Iris-versicolor  Iris-versicolor
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21   Iris-virginica  Iris-versicolor
22   Iris-virginica   Iris-virginica
23      Iris-setosa      Iris-setosa
24  Iris-versicolor  Iris-versicolor
25      Iris-setosa      Iris-setosa
26   Iris-virginica   Iris-virginica
27      Iris-setosa      Iris-setosa
28   Iris-virginica   Iris-virginica
29   Iris-virginica   Iris-virginica

In [103]:
# To identify correct K value

In [120]:
correct_sum = [] 
for i in range(1,20):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    pred = model.predict(x_test)
    correct = np.sum(pred == y_test)
    correct_sum.append(correct)

In [121]:
correct_sum

[np.int64(29),
 np.int64(26),
 np.int64(29),
 np.int64(28),
 np.int64(28),
 np.int64(27),
 np.int64(29),
 np.int64(27),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(27),
 np.int64(27),
 np.int64(27),
 np.int64(27),
 np.int64(27),
 np.int64(28)]

In [122]:
result = pd.DataFrame(data=correct_sum)
result.index = result.index+1
result.T

   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19
0  29  26  29  28  28  27  29  27  28  28  28  28  28  27  27  27  27  27  28

In [123]:
# K = 3 ganna

In [124]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
pred = model.predict(x_test)

In [125]:
accuracy_score(y_test,pred)

0.9666666666666667

In [126]:
confusion_matrix(y_test,pred)

array([[10,  0,  0],
       [ 0,  8,  0],
       [ 0,  1, 11]])